### ISSUE TITLE
external repo link target should be default browser

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/secretscanner-docker-extension#2]
**The problem**
clicking on deepfence github buttons, renders github inside the docker desktop.

**Expectation**
Upon clicking any of the two buttons, open the GitHub url in the default browser.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/18168330/194852814-f3c7e61d-d6c7-4742-99ea-36cce07cd82a.png">

**Comment by pandyamarut** [comment]
Assign this to me @ibreakthecloud

**Comment by ibreakthecloud** [comment]
> Assign this to me @ibreakthecloud

@pandyamarut Done. There's a similar issue if you want get that assigned too
https://github.com/deepfence/yarahunter-docker-extension/issues/3

**Comment by pandyamarut** [comment]
https://github.com/deepfence/secretscanner-docker-extension/pull/5 
@ibreakthecloud  Opened a Pull Request. Please take a look.
