### ISSUE TITLE
update README with development steps

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/secretscanner-docker-extension#3]
Add local development section in README with steps:
- to enable Chrome dev tool: console logs, network, source, etc.
- enable hot reloading: to use local ui code without rebuilding

ref: https://www.docker.com/blog/build-your-first-docker-extension/

**Comment by ighmaZ** [comment]
@ibreakthecloud ill do this

**Comment by ibreakthecloud** [comment]
> @ibreakthecloud ill do this

sure. Assigned!
