### ISSUE TITLE
Add blank slate and loading animation

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/secretscanner-docker-extension#4]
Add blank slate for the following conditions
- Initially when nothing is scanned
- When there is no result in the scan

Also, add animation in empty table view when scan is in progress

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/18168330/195048029-82c1c596-4eae-4723-9c09-9c7ca3033a5d.png">

**Comment by Le-Roi777** [comment]
Hi @ibreakthecloud :-) may I work on this enhancement?

**Comment by ibreakthecloud** [comment]
@Le-Roi777 Certainly :)

**Comment by Le-Roi777** [comment]
> @Le-Roi777 Certainly :)

Awesome! Keep you posted.
